name: Wasmpack-pages

env:
  CARGO_TERM_COLOR: always

runs:
  using: "composite"
    
  steps:
    - uses: actions/checkout@v4
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ./target/
          ./Cargo.lock
        key: ${{ runner.os }}-build-cache-wasm

    - name: Install wasmpack
      shell: bash
      run: cargo install wasm-pack

    - name: Build
      shell: bash
      run: wasm-pack build --release --target web
  
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: pkg/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
